apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: javaapp-container
          image: __REGISTRY__/javaapp:__IMAGEVERSION__
          ports:
            - name: javaappport
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
  namespace: default
spec:
  selector:
    app: javaapp
  ports:
    - name: javaappport
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
